name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: eshoponweb-ci-cd-gd7-mpd
  LOCATION: eastasia
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: a3846dd4-0856-4b8c-aac7-43f110bce070
  WEBAPP_NAME: eshoponweb-webapp-mpd-gd7

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o "${{ runner.temp }}/myapp"
          cd "${{ runner.temp }}/myapp"
          zip -r "${{ runner.temp }}/app.zip" .

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ runner.temp }}/app.zip

      - name: Upload bicep template artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: Development

    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: artifacts

      - name: Download bicep artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure (Bicep)
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: bicep-template/webapp.bicep
          parameters: >
            webAppName=${{ env.WEBAPP_NAME }}
            location=${{ env.LOCATION }}
          failOnStdErr: false

      - name: Deploy ZIP to WebApp (CLI)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name "${{ env.WEBAPP_NAME }}" \
              --resource-group "${{ env.RESOURCE_GROUP }}" \
              --src-path "artifacts/app.zip" \
              --type zip
